export const EVENT_TYPES = [
  { id: 'club', icon: '🎵', label: 'Club Night', desc: 'Seară de club cu DJ sau formație' },
  { id: 'festival', icon: '🎪', label: 'Festival', desc: 'Festival de muzică în aer liber' },
  { id: 'popup', icon: '⚡', label: 'Pop-Up Event', desc: 'Eveniment concept de câteva ore, locație inedită' },
  { id: 'citydays', icon: '🎆', label: 'City Days / Open Air', desc: 'Zilele orașului, eveniment municipal în aer liber' },
  { id: 'dinner_show', icon: '🍽️', label: 'Dinner & Show', desc: 'Cină elegantă cu spectacol live' },
  { id: 'nunta', icon: '💍', label: 'Nuntă', desc: 'Petrecere de nuntă' },
  { id: 'botez', icon: '👶', label: 'Botez', desc: 'Petrecere de botez' },
  { id: 'rooftop', icon: '🏙️', label: 'Rooftop', desc: 'Petrecere pe acoperiș' },
  { id: 'brunch', icon: '☕', label: 'Brunch', desc: 'Brunch muzical de zi' },
  { id: 'beach', icon: '🌊', label: 'Beach Party', desc: 'Petrecere pe plajă sau la mare' },
  { id: 'corporate', icon: '🏢', label: 'Corporate', desc: 'Eveniment de companie, team building, lansare' },
  { id: 'private', icon: '🎉', label: 'Petrecere privată', desc: 'Majorat, aniversare, petrecere surpriză' },
  { id: 'gala', icon: '🥂', label: 'Gală / Revelion / Crăciun', desc: 'Gală elegantă, revelion sau petrecere de sărbători' },
  { id: 'concert', icon: '🎤', label: 'Concert', desc: 'Concert live dedicat' },
  { id: 'nunta_botez', icon: '👶', label: 'Botez', desc: 'Petrecere de botez' },
  { id: 'altele', icon: '✨', label: 'Altele', desc: 'Descrie tu ce ai în minte' },
  { id: 'expert', icon: '🎯', label: 'Vorbește cu un expert', desc: 'Nu știi exact ce vrei? Te ajutăm noi' },
]

export const VIBES = [
  { id: 'luxury', icon: '💎', label: 'Luxury & Premium', desc: 'Cannes, Mykonos, Saint-Tropez. Știi tu.' },
  { id: 'sunset', icon: '🌅', label: 'Sunset Vibe', desc: 'Hi Ibiza. Ora magică când muzica și cerul se întâlnesc.' },
  { id: 'festival', icon: '🎪', label: 'Festival Energy', desc: 'Coachella feeling. Libertate, mulțime, amintiri pe viață.' },
  { id: 'day_party', icon: '☀️', label: 'Day Party', desc: 'Mykonos pool energy. Soarele sus, bassul tare.' },
  { id: 'beach', icon: '🌊', label: 'Beach Vibes', desc: 'Nisip, apă sărată, DJ în față. Vara la maxim.' },
  { id: 'brunch', icon: '☕', label: 'Brunch & Chill', desc: 'Lazy Sunday done right. Bună dispoziție fără grabă.' },
  { id: 'elegant', icon: '🕊️', label: 'Elegant & Rafinat', desc: 'Black tie optional. Clasă fără efort.' },
  { id: 'underground', icon: '🌑', label: 'Underground', desc: 'Berghain energy. Nu e pentru toată lumea.' },
  { id: 'rooftop', icon: '🏙️', label: 'Rooftop Cool', desc: 'Orașul la picioare. Vibe urban pe acoperiș.' },
  { id: 'mainstream', icon: '🎊', label: 'Mainstream Party', desc: 'Toată lumea știe versurile. Toată lumea cântă.' },
  { id: 'balkan', icon: '⚡', label: 'Balkan Energy', desc: 'Nu poți sta liniștit. Nici nu vrei.' },
  { id: 'afro', icon: '🌍', label: 'Afro Vibes', desc: 'Afrobeats & groove. Ritm care te mișcă fără să vrei.' },
  { id: 'imersiv', icon: '🎭', label: 'Imersiv & Spectacol', desc: 'Nu e concert. E o altă lume.' },
  { id: 'nostalgic', icon: '📻', label: 'Nostalgic & Retro', desc: 'Hiturile anilor 2000. Le știi toate. Le cânți pe toate.' },
  { id: 'wellness', icon: '🌿', label: 'Wellness Rave', desc: 'Energie pură. Minte clară. Corp în mișcare.' },
  { id: 'dinner_show', icon: '🍽️', label: 'Dinner & Show', desc: 'O seară completă. Dining rafinat, entertainment live și artiști aleși pe sprânceană.' },
]

// Matching: Event → Vibe-uri sugerate (apar primele)
export const EVENT_VIBE_MAP: Record<string, string[]> = {
  'club': ['underground', 'rooftop', 'afro', 'day_party', 'sunset', 'mainstream'],
  'festival': ['festival', 'mainstream', 'balkan', 'nostalgic', 'imersiv', 'afro'],
  'citydays': ['festival', 'mainstream', 'balkan', 'nostalgic', 'imersiv'],
  'popup': ['underground', 'day_party', 'afro', 'sunset', 'wellness'],
  'dinner_show': ['dinner_show', 'luxury', 'elegant', 'imersiv'],
  'nunta': ['elegant', 'dinner_show', 'mainstream', 'balkan', 'luxury'],
  'botez': ['elegant', 'mainstream', 'balkan'],
  'rooftop': ['rooftop', 'sunset', 'luxury', 'day_party', 'afro'],
  'brunch': ['brunch', 'sunset', 'day_party', 'rooftop', 'luxury'],
  'beach': ['beach', 'day_party', 'sunset', 'afro', 'mainstream'],
  'corporate': ['elegant', 'luxury', 'dinner_show', 'imersiv', 'mainstream'],
  'private': ['mainstream', 'balkan', 'nostalgic', 'luxury', 'elegant'],
  'gala': ['luxury', 'elegant', 'dinner_show', 'mainstream', 'imersiv'],
  'concert': ['festival', 'imersiv', 'mainstream', 'nostalgic'],
}

export const GENRES = [
  { id: 'afro_house', label: 'Afro House', category: 'Electronic' },
  { id: 'tech_house', label: 'Tech House', category: 'Electronic' },
  { id: 'deep_house', label: 'Deep House', category: 'Electronic' },
  { id: 'melodic_house', label: 'Melodic House', category: 'Electronic' },
  { id: 'house', label: 'House', category: 'Electronic' },
  { id: 'indie_dance', label: 'Indie Dance', category: 'Electronic' },
  { id: 'dance', label: 'Dance', category: 'Electronic' },
  { id: 'edm', label: 'EDM', category: 'Electronic' },
  { id: 'techno', label: 'Techno', category: 'Electronic' },
  { id: 'disco_funk', label: 'Disco / Funk', category: 'Electronic' },
  { id: 'lounge', label: 'Lounge / Chill', category: 'Electronic' },
  { id: 'manele', label: 'Manele', category: 'Românesc' },
  { id: 'muzica_petrecere', label: 'Muzică de petrecere', category: 'Românesc' },
  { id: 'populara', label: 'Populară românească', category: 'Românesc' },
  { id: 'etno_balkan', label: 'Etno / Balkan', category: 'Românesc' },
  { id: 'afro_manele', label: 'Afro Manele', category: 'Românesc' },
  { id: 'balkan_afro', label: 'Balkan Afro', category: 'Românesc' },
  { id: 'hora_sarba', label: 'Horă / Sârbă', category: 'Românesc' },
  { id: 'greceasca', label: 'Muzică grecească', category: 'Românesc' },
  { id: 'slagare', label: 'Șlagăre românești', category: 'Românesc' },
  { id: 'romante', label: 'Romanțe', category: 'Românesc' },
  { id: 'hiphop', label: 'Hip-Hop', category: 'Urban' },
  { id: 'trap', label: 'Trap', category: 'Urban' },
  { id: 'urban', label: 'Urban', category: 'Urban' },
  { id: 'rnb', label: 'R&B', category: 'Urban' },
  { id: 'reggaeton', label: 'Reggaeton', category: 'Urban' },
  { id: 'latino', label: 'Latino', category: 'Urban' },
  { id: 'afrobeats', label: 'Afrobeats', category: 'Urban' },
  { id: 'pop', label: 'Pop', category: 'Internațional' },
  { id: 'rock', label: 'Rock', category: 'Internațional' },
  { id: 'indie', label: 'Indie / Alternative', category: 'Internațional' },
  { id: 'jazz', label: 'Jazz', category: 'Internațional' },
  { id: 'blues', label: 'Blues', category: 'Internațional' },
  { id: 'clasica', label: 'Clasică / Orchestral', category: 'Internațional' },
  { id: 'neo_soul', label: 'Neo-Soul', category: 'Internațional' },
  { id: 'nostalgic', label: 'Nostalgic / Retro', category: 'Internațional' },
  { id: 'ambient', label: 'Ambient', category: 'Internațional' },
  { id: 'live_band', label: 'Live Band', category: 'Live' },
  { id: 'cover_band', label: 'Cover Band', category: 'Live' },
  { id: 'formatie_nunta', label: 'Formație nuntă', category: 'Live' },
  { id: 'taraf', label: 'Taraf / Lăutari', category: 'Live' },
  { id: 'fanfara', label: 'Fanfară', category: 'Live' },
  { id: 'open_format', label: 'Open Format', category: 'Live' },
  { id: 'acoustic', label: 'Acoustic', category: 'Live' },
  { id: 'silent_disco', label: 'Silent Disco', category: 'Live' },
]

export const GENRE_CATEGORIES = ['Electronic', 'Românesc', 'Urban', 'Internațional', 'Live']

export const FORMATS = [
  { id: 'dj_set', label: 'DJ Set', category: 'DJ & Mixing' },
  { id: 'dj_hibrid', label: 'DJ Set Hibrid', category: 'DJ & Mixing' },
  { id: 'open_format', label: 'Open Format', category: 'DJ & Mixing' },
  { id: 'formatie_nunta', label: 'Formație nuntă / Cover Band', category: 'Formații & Trupe' },
  { id: 'acoustic', label: 'Acoustic', category: 'Formații & Trupe' },
  { id: 'orchestra', label: 'Orchestră', category: 'Formații & Trupe' },
  { id: 'cvartet', label: 'Cvartet de coarde', category: 'Formații & Trupe' },
  { id: 'cor', label: 'Cor / Grup vocal', category: 'Formații & Trupe' },
  { id: 'taraf', label: 'Taraf / Lăutari', category: 'Formații & Trupe' },
  { id: 'solist', label: 'Solist / Solistă', category: 'Soliști & Voci' },
  { id: 'mc', label: 'MC / Prezentator', category: 'Soliști & Voci' },
  { id: 'sax_live', label: 'Sax Live', category: 'Instrumente Live' },
  { id: 'vioara_live', label: 'Vioară Live', category: 'Instrumente Live' },
  { id: 'percutie_live', label: 'Percuție / Tobe Live', category: 'Instrumente Live' },
  { id: 'pian_live', label: 'Pian Live', category: 'Instrumente Live' },
  { id: 'trompeta_live', label: 'Trompetă Live', category: 'Instrumente Live' },
  { id: 'dansatori', label: 'Dansatori', category: 'Show & Special Acts' },
  { id: 'efecte_speciale', label: 'Efecte speciale', category: 'Show & Special Acts' },
  { id: 'magician', label: 'Magician / Iluzionist / Mentalist', category: 'Show & Special Acts' },
  { id: 'animatori_copii', label: 'Animatori copii', category: 'Show & Special Acts' },
]

export const FORMAT_CATEGORIES = ['DJ & Mixing', 'Formații & Trupe', 'Soliști & Voci', 'Instrumente Live', 'Show & Special Acts']

export const GENRE_FORMAT_MAP: Record<string, string[]> = {
  'afro_house': ['dj_set', 'dj_hibrid', 'open_format', 'percutie_live', 'sax_live', 'dansatori', 'efecte_speciale'],
  'tech_house': ['dj_set', 'dj_hibrid', 'open_format', 'percutie_live', 'efecte_speciale', 'dansatori'],
  'deep_house': ['dj_set', 'dj_hibrid', 'open_format', 'sax_live', 'vioara_live', 'pian_live'],
  'melodic_house': ['dj_set', 'dj_hibrid', 'open_format', 'vioara_live', 'pian_live', 'sax_live'],
  'house': ['dj_set', 'dj_hibrid', 'open_format', 'percutie_live', 'sax_live', 'dansatori'],
  'indie_dance': ['dj_set', 'dj_hibrid', 'open_format', 'acoustic'],
  'dance': ['dj_set', 'dj_hibrid', 'open_format', 'percutie_live', 'dansatori', 'efecte_speciale'],
  'edm': ['dj_set', 'dj_hibrid', 'open_format', 'percutie_live', 'efecte_speciale', 'dansatori'],
  'techno': ['dj_set', 'dj_hibrid', 'percutie_live', 'efecte_speciale'],
  'disco_funk': ['dj_set', 'dj_hibrid', 'open_format', 'formatie_nunta', 'sax_live', 'percutie_live', 'dansatori'],
  'lounge': ['dj_set', 'open_format', 'acoustic', 'pian_live', 'sax_live', 'vioara_live', 'cvartet'],
  'manele': ['solist', 'formatie_nunta', 'taraf', 'mc', 'dj_set'],
  'muzica_petrecere': ['formatie_nunta', 'solist', 'taraf', 'mc', 'dj_set', 'open_format'],
  'populara': ['solist', 'formatie_nunta', 'taraf', 'mc', 'orchestra'],
  'etno_balkan': ['taraf', 'formatie_nunta', 'solist', 'percutie_live', 'dj_hibrid'],
  'afro_manele': ['dj_set', 'dj_hibrid', 'solist', 'percutie_live', 'dansatori'],
  'balkan_afro': ['dj_set', 'dj_hibrid', 'percutie_live', 'solist', 'dansatori'],
  'hora_sarba': ['taraf', 'formatie_nunta', 'solist', 'mc'],
  'greceasca': ['formatie_nunta', 'solist', 'taraf'],
  'slagare': ['solist', 'formatie_nunta', 'orchestra', 'mc'],
  'romante': ['solist', 'acoustic', 'cvartet', 'orchestra', 'pian_live', 'vioara_live'],
  'hiphop': ['dj_set', 'dj_hibrid', 'open_format', 'mc', 'percutie_live', 'dansatori'],
  'trap': ['dj_set', 'dj_hibrid', 'open_format', 'mc', 'percutie_live', 'efecte_speciale'],
  'urban': ['dj_set', 'dj_hibrid', 'open_format', 'mc', 'solist', 'percutie_live'],
  'rnb': ['dj_set', 'dj_hibrid', 'open_format', 'solist', 'mc', 'pian_live'],
  'reggaeton': ['dj_set', 'dj_hibrid', 'open_format', 'percutie_live', 'dansatori', 'mc'],
  'latino': ['dj_set', 'dj_hibrid', 'formatie_nunta', 'percutie_live', 'dansatori'],
  'afrobeats': ['dj_set', 'dj_hibrid', 'open_format', 'percutie_live', 'dansatori', 'efecte_speciale'],
  'pop': ['dj_set', 'dj_hibrid', 'open_format', 'solist', 'formatie_nunta', 'acoustic', 'mc'],
  'rock': ['formatie_nunta', 'acoustic', 'trompeta_live', 'percutie_live'],
  'indie': ['acoustic', 'formatie_nunta', 'dj_set'],
  'jazz': ['acoustic', 'pian_live', 'sax_live', 'vioara_live', 'trompeta_live', 'cvartet', 'cor'],
  'blues': ['acoustic', 'formatie_nunta', 'pian_live', 'percutie_live'],
  'clasica': ['orchestra', 'cvartet', 'cor', 'pian_live', 'vioara_live', 'acoustic'],
  'neo_soul': ['solist', 'acoustic', 'pian_live', 'dj_set'],
  'nostalgic': ['dj_set', 'open_format', 'formatie_nunta', 'solist', 'orchestra'],
  'ambient': ['dj_set', 'acoustic', 'pian_live', 'vioara_live'],
  'live_band': ['formatie_nunta', 'dj_hibrid', 'mc', 'solist'],
  'cover_band': ['formatie_nunta', 'mc', 'solist', 'dj_hibrid'],
  'formatie_nunta': ['formatie_nunta', 'solist', 'mc', 'taraf', 'dj_set'],
  'taraf': ['taraf', 'solist', 'mc', 'formatie_nunta'],
  'fanfara': ['taraf', 'mc'],
  'open_format': ['dj_set', 'dj_hibrid', 'open_format'],
  'acoustic': ['acoustic', 'solist', 'pian_live', 'vioara_live', 'sax_live'],
  'silent_disco': ['dj_set', 'open_format'],
}

export const GENRE_FORMAT_TAB: Record<string, string> = {
  'afro_house': 'DJ & Mixing', 'tech_house': 'DJ & Mixing', 'deep_house': 'DJ & Mixing',
  'melodic_house': 'DJ & Mixing', 'house': 'DJ & Mixing', 'indie_dance': 'DJ & Mixing',
  'dance': 'DJ & Mixing', 'edm': 'DJ & Mixing', 'techno': 'DJ & Mixing',
  'disco_funk': 'DJ & Mixing', 'lounge': 'DJ & Mixing',
  'manele': 'Formații & Trupe', 'muzica_petrecere': 'Formații & Trupe',
  'populara': 'Formații & Trupe', 'etno_balkan': 'Formații & Trupe',
  'afro_manele': 'DJ & Mixing', 'balkan_afro': 'DJ & Mixing',
  'hora_sarba': 'Formații & Trupe', 'greceasca': 'Formații & Trupe',
  'slagare': 'Soliști & Voci', 'romante': 'Soliști & Voci',
  'hiphop': 'DJ & Mixing', 'trap': 'DJ & Mixing', 'urban': 'DJ & Mixing',
  'rnb': 'DJ & Mixing', 'reggaeton': 'DJ & Mixing', 'latino': 'DJ & Mixing',
  'afrobeats': 'DJ & Mixing', 'pop': 'DJ & Mixing', 'rock': 'Formații & Trupe',
  'indie': 'Formații & Trupe', 'jazz': 'Instrumente Live', 'blues': 'Instrumente Live',
  'clasica': 'Formații & Trupe', 'neo_soul': 'Soliști & Voci',
  'nostalgic': 'DJ & Mixing', 'ambient': 'DJ & Mixing',
  'live_band': 'Formații & Trupe', 'cover_band': 'Formații & Trupe',
  'formatie_nunta': 'Formații & Trupe', 'taraf': 'Formații & Trupe',
  'fanfara': 'Formații & Trupe', 'open_format': 'DJ & Mixing',
  'acoustic': 'Formații & Trupe', 'silent_disco': 'DJ & Mixing',
}

export const VIBE_FORMAT_TAB: Record<string, string> = {
  'luxury': 'Formații & Trupe', 'sunset': 'DJ & Mixing', 'festival': 'DJ & Mixing',
  'day_party': 'DJ & Mixing', 'beach': 'DJ & Mixing', 'brunch': 'Formații & Trupe',
  'elegant': 'Formații & Trupe', 'underground': 'DJ & Mixing', 'rooftop': 'DJ & Mixing',
  'mainstream': 'DJ & Mixing', 'balkan': 'Formații & Trupe', 'afro': 'DJ & Mixing',
  'imersiv': 'DJ & Mixing', 'nostalgic': 'Formații & Trupe', 'wellness': 'DJ & Mixing',
  'dinner_show': 'Formații & Trupe',
}

export const FORMAT_COMPATIBILITY: Record<string, string[]> = {
  'luxury': ['orchestra', 'cvartet', 'acoustic', 'pian_live', 'vioara_live', 'sax_live', 'dj_hibrid', 'solist', 'magician', 'dansatori'],
  'sunset': ['dj_set', 'dj_hibrid', 'open_format', 'acoustic', 'sax_live', 'vioara_live'],
  'festival': ['dj_set', 'dj_hibrid', 'open_format', 'formatie_nunta', 'mc', 'percutie_live', 'efecte_speciale', 'dansatori'],
  'day_party': ['dj_set', 'dj_hibrid', 'open_format', 'percutie_live', 'sax_live', 'dansatori', 'mc'],
  'beach': ['dj_set', 'dj_hibrid', 'open_format', 'percutie_live', 'dansatori', 'mc', 'sax_live'],
  'brunch': ['acoustic', 'dj_set', 'open_format', 'pian_live', 'sax_live', 'vioara_live', 'solist'],
  'elegant': ['orchestra', 'cvartet', 'acoustic', 'pian_live', 'vioara_live', 'solist', 'cor', 'magician'],
  'underground': ['dj_set', 'dj_hibrid', 'percutie_live', 'efecte_speciale'],
  'rooftop': ['dj_set', 'dj_hibrid', 'open_format', 'acoustic', 'sax_live', 'mc'],
  'mainstream': ['dj_set', 'open_format', 'formatie_nunta', 'solist', 'mc', 'dansatori', 'efecte_speciale'],
  'balkan': ['taraf', 'formatie_nunta', 'solist', 'percutie_live', 'dj_hibrid', 'mc', 'dansatori'],
  'afro': ['dj_set', 'dj_hibrid', 'open_format', 'percutie_live', 'dansatori', 'sax_live'],
  'imersiv': ['dj_set', 'dj_hibrid', 'efecte_speciale', 'dansatori', 'magician', 'percutie_live', 'mc'],
  'nostalgic': ['formatie_nunta', 'solist', 'orchestra', 'dj_set', 'open_format', 'acoustic', 'mc'],
  'wellness': ['dj_set', 'dj_hibrid', 'open_format', 'percutie_live', 'acoustic'],
  'dinner_show': ['orchestra', 'cvartet', 'acoustic', 'solist', 'magician', 'dansatori', 'pian_live', 'vioara_live'],
}

export const CAPACITY_RANGES_VENUE = [
  { label: '100–200', min: 100, max: 200 },
  { label: '200–400', min: 200, max: 400 },
  { label: '400–700', min: 400, max: 700 },
  { label: '700–1000', min: 700, max: 1000 },
  { label: '1000–1500', min: 1000, max: 1500 },
  { label: '1500–2000', min: 1500, max: 2000 },
  { label: '2000+', min: 2000, max: 4000 },
  { label: '4000+', min: 4000, max: 7000 },
  { label: '7000+', min: 7000, max: 9000 },
  { label: '9000+', min: 9000, max: 999999 },
]

export const CAPACITY_WEDDING = [100, 150, 200, 250, 350, 400, 600, 1000]

export const TIERS = [
  { id: 'premium', label: 'Premium', desc: '10.000€+', color: '#f59e0b', bg: '#fef3c7' },
  { id: 'aplus', label: 'A+', desc: '7.000–9.999€', color: '#3b82f6', bg: '#eff6ff' },
  { id: 'a', label: 'A', desc: 'sub 7.000€', color: '#6b7280', bg: '#f5f5f4' },
]